### ISSUE TITLE
Prune tool doesn't appear to work

### ISSUE THREAD

**Issue by jessp** [skomputer/oligrapher#41]
Does not work in dev version or demo (hosted at [http://oli2.littlesis.org/](http://oli2.littlesis.org/)), and works inconsistently in official version on LittleSis website.

**Comment by aepyornis** [comment]
FYI: that demo version uses an outdated version of Oligrapher.

**Comment by jessp** [comment]
Yep, I'm aware. I was checking to see if it was something that was recently-ish broken.

**Comment by jessp** [comment]
Looking at this now. In the interest of documenting progress, I'm finding that the prune tools works on nodes that are added from the database (e.g. selected from the dropdown list that appears when searching), but doesn't work on custom-named nodes.
